# Generated by Django 6.0.1 on 2026-09-19 21:32

from django.db import migrations


def seed_default_config(apps, schema_editor):
    TournamentConfig = apps.get_model('merch', 'TournamentConfig')
    if not TournamentConfig.objects.filter(pk=1).exists():
        TournamentConfig.objects.create(
            pk=1,
            tournament_name='EYT GAMER ARMY TOURNAMENT',
            fee_amount=0,
            currency='NGN',
            account_name='',
            account_number='',
            bank_name='',
            max_participants=0,
            is_registration_open=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_tournamentconfig_tournamentregistration'),
    ]

    operations = [
        migrations.RunPython(seed_default_config),
    ]